name: toEpitechCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testLaunchRedditech:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk lib/src/main.dart
      - name: Change build apk name
        run: mv ./build/app/outputs/flutter-apk/app-release.apk qwiddo.apk
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.4
        with:
         path: qwiddo.apk

  pushOnEpitech:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1.0.1
        if: github.repository == '0Nom4D/Qwiddo'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        with:
          source-repo: git@github.com:0Nom4D/Qwiddo.git
          destination-repo: git@github.com:EpitechPromo2024/B-DEV-501-NAN-5-1-redditech-arthur.adam.git
